# Generated by Django 5.2.7 on 2025-10-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='required_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipped_date',
            field=models.DateTimeField(),
        ),
    ]
